### ISSUE TITLE
The fusilli-env needs to be re-activated every time. (Correct?)

### ISSUE THREAD

**Issue by hegde00** [florencejt/fusilli#30]
Hello,

Fusilli is terrific. The instructions on the fusilli website were very clear and helpful. However, I'd like to note here a couple of things which were not clear to me from the instructions, so that newbies to fusilli like me can benefit from it (i.e., these are not problems per se, just notable issues, that's all):

(1) If you successfully install fusilli virtual environment, and log out of it, you still have *reactivate* the virtual environment before you can use the virtual environment again (as best as I can tell, from my experience on a Windows 11 Professional 64-bit machine).
      I was expecting that you can simply re-enter the virtual environment using a command like
                 c:\Users\Me> virtualenv fusilli-env
     Similar commands work for me for other virtual environments, but not for fusilli.

(2) Also, there is activate.exe in fusilli install (as noted in the install instructions). So I activated it successfully using the batch file named ./fusilli/fusilli-env/Scripts/activate.bat

Thanks again for sharing a terrific tool like fusilli!

**Comment by florencejt** [comment]
Hi!

Thank you so much for the kind words about Fusilli! I'm glad to hear that you're finding it useful and that the instructions were clear overall. They were a lot of fun to write :)

Let me address the points you raised:  

### 1. Reactivating the Virtual Environment  
You're absolutely right—once you log out of a virtual environment, you need to reactivate it to use it again. However, the command `virtualenv fusilli-env` is for creating a new virtual environment, not re-entering an existing one. To reactivate your Fusilli environment, you’ll need to use the activation script for your operating system:  

- **On Windows:**  
  ```cmd
  .\fusilli-env\Scripts\activate.bat

- **On Linux/MacOS:**  
  ```cmd
  source fusilli-env/bin/activate

I'll update the documentation to make this process clearer and ensure there's no confusion about reactivating vs. recreating environments.

### 2. Using `activate.exe`
It looks like there’s a bit of a mix-up here—virtual environments created with `venv` typically provide an `activate.bat` script for Windows, not an `activate.exe`. It sounds like you’ve already figured out how to use the batch file (`.\fusilli-env\Scripts\activate.bat`), which is the correct approach. I’ll clarify this in the documentation as well to avoid similar confusion in the future.

Thanks again for your feedback! And please let me know if this works and clears it up for you?

Best,
Florence 🌸

**Comment by hegde00** [comment]
Thank you very much for the clarifications!
